### ISSUE TITLE
Trying to beautify code with syntax error erases the whole code

### ISSUE THREAD

**Issue by RafaArantes** [LukasMeine/universal-code-beautifier#1]
Replaces the code with the following json

```
{
    "status": 400,
    "message": "File extension not supported"
}
```

**Comment by conilas** [comment]
Upvoted. Had the same issue.

**Comment by conilas** [comment]
Pull request willing to correct the issue: https://github.com/LukasMeine/universal-code-beautifier/pull/2

**Comment by conilas** [comment]
@LukasMeine pls close
